config/routes.rb
Blow::Application.routes.draw do

  resources :videos

  mount Ckeditor::Engine => '/ckeditor'

resources :pages
resources :post_categories
root :to => "posts#index"
devise_for :users
resources :users, :only => [:show, :index]
match "/posts/tag/:id" => "posts#tag", :as => :tag_posts
resources :posts do
collection do
  get :tag
  get :tags
end
end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
    acts_as_nested_set

    attr_accessible :name, :description, :lft, :rgt, :parent_id   

    has_many :categorizations
    has_many :posts, :through => :categorizations

    attr_accessor :_list

    def branch_ids
      self_and_descendants.map(&:id).uniq 
    end

    def all_products
       Product.find(:all, :conditions => { :category_id => branch_ids } )
    end


end

app/controllers/post_categories_controller.rb
class PostCategoriesController < InheritedResources::Base
  
# GET /categories
  # GET /categories.xml
  def index
    @post_categories = PostCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @post_categories }
    end
  end
  
    # GET /categories/new
  # GET /categories/new.xml
  def new
    @post_category = PostCategory.new
  
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post_category }
    end
  end
  
    # POST /categories
  # POST /categories.xml
  def create
    @post_category = PostCategory.new(params[:post_category])
  
    respond_to do |format|
      if @post_category.save
        format.html { redirect_to(@post_category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @post_category, :status => :created, :location => @post_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post_category.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
end

app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

app/views/post_categories/_form.html.erb
<%= form_for(@post_category) do |f| %>
  <% if @post_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_category.errors.count, "error") %> prohibited this post_category from being saved:</h2>

      <ul>
      <% @post_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_categories/edit.html.erb
<h1>Editing post_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_category %> |
<%= link_to 'Back', post_categories_path %>

app/views/post_categories/index.html.erb
<h1>Listing Post Categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post_categories.each do |post_category| %>
  <tr>
    <td><%= post_category.name %></td>
    <td><%= post_category.description %></td>
    <td><%= link_to 'Show', post_category %></td>
    <td><%= link_to 'Edit', edit_post_category_path(post_category) %></td>
    <td><%= link_to 'Destroy', post_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post category', new_post_category_path %>

app/views/post_categories/new.html.erb
<h1>New post_category</h1>

<%= render 'form' %>

<%= link_to 'Back', post_categories_path %>

app/views/post_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post_category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @post_category.description %>
</p>


<%= link_to 'Edit', edit_post_category_path(@post_category) %> |
<%= link_to 'Back', post_categories_path %>