config/routes.rb
Blow::Application.routes.draw do

  resources :videos

  mount Ckeditor::Engine => '/ckeditor'

resources :pages
resources :post_categories
root :to => "posts#index"
devise_for :users
resources :users, :only => [:show, :index]
match "/posts/tag/:id" => "posts#tag", :as => :tag_posts
resources :posts do
collection do
  get :tag
  get :tags
end
end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
 
    if user.role? :admin
      can :manage, :all
      can :publish, Post
    elsif user.role? :moderator
      can :manage, :all
    elsif user.role? :member
       can :read, :all
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
end



ActiveAdmin.register AdminUser do
  index do
    # ...
  end
 
  form do |f|
    f.inputs "Admin Details" do
      f.input :email
      f.input :password
      f.input :password_confirmation
    end
    f.buttons
  end
  

end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :body, :title
  validates_presence_of :title, :body
  validates_uniqueness_of :title
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :post_category
  #Friendly ID
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
 
  #def shoud_generate_new_friendly_id?
   # new_record?
  #end
 
  attr_accessible :body, :title, :user_id, :published, :tag_list, :tag_tokens, :category_id, :parent_id
  belongs_to :user
  validates_presence_of :title, :body
  validates_uniqueness_of :title
  validates_numericality_of :user_id

  
  scope :published, lambda { {:conditions => ['published = ?', true]} }
  scope :ordered, lambda {{:order => "Created_at DESC" }}
  
  acts_as_taggable_on :tags # Tagging p
  attr_reader :tag_tokens
  
  def tag_tokens=(ids)
    tags = ids.split(",")
    #Holder for existing tag ids
    finder = []
    #Holder for new tag strings
    r_tags = []
    for tag in tags
      if tag.to_i > 0
        finder << tag
      else
        r_tags << tag.delete("'")
      end
    end
    #Find existing tags from integer ids
    r_tags += ActsAsTaggableOn::Tag.select(:name).find(finder).collect(&:name)
    self.tag_list = r_tags
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
    acts_as_nested_set

    attr_accessible :name, :description, :lft, :rgt, :parent_id   

    has_many :categorizations
    has_many :posts, :through => :categorizations

    attr_accessor :_list

    def branch_ids
      self_and_descendants.map(&:id).uniq 
    end

    def all_products
       Product.find(:all, :conditions => { :category_id => branch_ids } )
    end


end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  has_and_belongs_to_many :roles
  acts_as_tagger
  has_many :posts
  
  #Find Role by String Name
  def role?(role)
   return !!self.roles.find_by_name(role.to_s)
  end
  
  #Add Role to User During Registration
  before_create :setup_role
  private
  def setup_role
    if self.role_ids.empty?
      self.role_ids = [3]
    end
  end
  
  
  
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :body, :category_id, :slug, :title, :url, :user_id
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  @users = User.all
end

end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
before_filter :authenticate_user!, :except => [:index, :show, :tag]

  # GET /articles
  # GET /articles.xml
  def index
    @posts = Post.published.page(params[:page]).per(5).ordered
        
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end
def tag
    @posts = Post.tagged_with(params[:id]).page(params[:page])
    render :index
  end
#Acts as Taggable Tag Creation InputToken
def tags
    query = params[:q]
    if query[-1,1] == " "
      query = query.gsub(" ", "")
      Tag.find_or_create_by_name(query)
    end

    #Do the search in memory for better performance

    @tags = ActsAsTaggableOn::Tag.all
    @tags = @tags.select { |v| v.name =~ /#{query}/i }
    respond_to do |format|
      format.json{ render :json => @tags.map(&:attributes) }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @post = Post.find(params[:id])
    
    #Friendly ID Redirect Old Slugs
    if request.path != post_path(@post)
      redirect_to @post, status: :moved_permanently
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
 
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /articles/1/edit
  def edit
    @post = Post.find(params[:id])
    authorize! :edit, @post
  end

  # POST /articles
  # POST /articles.xml
  def create
    authorize! :create, @post
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    @post = Post.create(params[:post_category])
    @post.post_category = PostCategory.find(params[:category_id]) if params[:category_id]
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @post = Post.find(params[:id])
  authorize! :update, @post
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
  

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <% if current_user.role? :admin %>
      <li>
      <%= link_to('Admin', users_path) %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BLOW! Hip Hop" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    
    <%= stylesheet_link_tag "application", "token-input-facebook" %>
	<%= javascript_include_tag :defaults, "jquery.tokeninput" %>
    
    
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "ckeditor/init" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    
    
  </head>
  <body>  	
  <div id="container-fluid">
  	<%= link_to "BLOW! Hip Hop", root_path, :id => 'topleft' %>
  	
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container-fluid">
        	<div class="nav pull-left social_icons"> 
        		<a href="#"><img src="/img/Twitter.png" alt="Twitter"></a>
        
                  <a href="#"><img src="/img/Facebook.png"  alt="Facebook"></a>
        
                  <a href="#"><img src="/img/Tumblr.png"  alt="Tumblr"></a>
        
                  <a href="#"><img src="/img/YouTube.png" alt="YouTube"></a>
        
          </div>
          <form class="navbar-search pull-right">
  <input type="text" class="search-query" placeholder="Search">
      </form>
     
        <div class="pull-right login">
		<%= render 'layouts/navigation' %>
        </div>
          
        </div>
      </nav>
    </header>
    <div class="sidebar left">
<!--Sidebar content-->

<ul class="nav nav-list">
        
          <li><%= link_to('Blog', posts_path)  %></li>

          <!--<li class="nav-header">My Block</li>
          <li><a href="#"><i class="icon-user"></i> Profile</a></li>
           <li><a href="#"><i class="icon-user"></i> Connects</a></li>
          <li><a href="#"><i class="icon-cog"></i> Settings</a></li>
          <li><a href="#"><i class="icon-flag"></i> Help</a></li>-->

    </ul>
        <ul class="invite">
        	<li><a href="#">Invite Friends</a></li>
        </ul>



</div>
<div class="sidebar_right"><img src="/img/300x250.gif" width="300" height="250" alt="300x250">
   
</div>
    <div id="main" role="main">
        <div class="content">
         
              <%= render 'layouts/messages'%>
              <%= yield %>
              
          <footer>
          </footer>
        
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
</div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.body %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Body:</b>
  <%= @page.body %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>